#include "hdtree.h"

#define print_text_test_result(call, text) printf("\n%i <- %s with %s", call, #call, text);

// Linking to the console subsystem executes a test on the tree object instead of calling WinMain() and launching the window
int main () {
	hd::MaterialTree		tree;

	constexpr const char*	testStrings[] = 
		{ "1"
		, "c"
		, "win.ini"
		, "WindowsUpdate.log"
		, "winhlp32.exe"
		, "mib.bin"
		, "Microsoft.NET"
		, "PLA"
		, "aa"
		, "bb"
		, "cc"
		, "ac"
		, "bbc"
		, "zab"
		, "aabz"
		, "cabasd"
		, "j"
		, "b"
		, "x"
		, "b"
		, "iii"
		, "i"
		, "addins"
		, "appcompat"
		, "BCW5.INI"
		, "bfsvc.exe"
		, "Boot"
		, "Branding"
		, "apppatch"
		, "AppReadiness"
		, "Containers"
		, "CSC"
		, "Cursors"
		, "DDACLSys.log"
		, "debug"
		, "Ascd_ProcessLog.ini"
		, "Ascd_tmp.ini"
		, "audio.log"
		, "bcastdvr"
		, "CbsTemp"
		, "comsetup.log"
		, "diagerr.xml"
		, "diagnostics"
		, "DiagTrack"
		, "diagwrn.xml"
		, "GameBarPresenceWriter"
		, "DigitalLocker"
		, "cab"
		, "DirectX.log"
		, "Downloaded Installations"
		, "gethelp_audiotroubleshooter_latestpackage.zip"
		, "glide2x.dll"
		, "Help"
		, "INF"
		, "bb"
		, "acb"
		, "bbc"
		, "b"
		, "glide3x.dll"
		, "a"
		, "acb"
		, "InfusedApps"
		, "system.ini"
		, "InputMethod"
		, "DPINST.LOG"
		, "OCR"
		, "DtcInstall.log"
		, "ehome"
		, "rescache"
		, "en"
		, "es-ES"
		, "Globalization"
		, "L2Schemas"
		, "LAN.log"
		, "LiveKernelReports"
		, "en-US"
		, "Logs"
		, "Migration"
		, "PrintDialog"
		, "Professional.xml"
		, "ca"
		, "progress.ini"
		, "ODBCINST.INI"
		, "Offline Web Pages"
		, "explorer.exe"
		, "splwow64.exe"
		, "Performance"
		, "System32"
		, "Minidump"
		, "Panther"
		, "MASetupCaller.dll"
		, "GearBox.ini"
		, "Provisioning"
		, "py.exe"
		, "SchCache"
		, "pyshellext.amd64.dll"
		, "pyw.exe"
		, "PFRO.log"
		, "regedit.exe"
		, "System"
		, "Resources"
		, "RtlExUpd.dll"
		, "HelpPane.exe"
		, "schemas"
		, "security"
		, "MAMCityDownload.ocx"
		, "Speech"
		, "Speech_OneCore"
		, "ModemLogs"
		, "msdfmap.ini"
		, "SystemResources"
		, "MusiccityDownload.exe"
		, "twain_32.dll"
		, "UpdateAssistant"
		, "ServiceProfiles"
		, "Vss"
		, "WaaS"
		, "Web"
		, "PolicyDefinitions"
		, "WLXPGSS.SCR"
		, "SysWOW64"
		, "Prefetch"
		, "ServiceState"
		, "servicing"
		, "SystemApps"
		, "Temp"
		, "TextInput"
		, "tracing"
		, "setuperr.log"
		, "twain_32"
		, "setupact.log"
		, "ShellExperiences"
		, "SystemTemp"
		, "notepad.exe"
		, "Setup"
		, "TAPI"
		, "Tasks"
		, "ShellNew"
		, "TSSysprep.log"
		, "hh.exe"
		, "IdentityCRL"
		, "WinSxS"
		, "IE11_main.log"
		, "ShellComponents"
		, "Registration"
		, "IME"
		, "RemotePackages"
		, "ImmersiveControlPanel"
		, "SKB"
		, "WMSysPr9.prx"
		, "SoftwareDistribution"
		, "write.exe"
		};

	for(const char* textToTest : testStrings)
		print_text_test_result(tree.AddCategory(textToTest), textToTest);

	for(const char* textToTest : testStrings)
		print_text_test_result(tree.Categories[0].AddMaterial(textToTest), textToTest);

	printf("\n\nCategory results:\n");
	for(auto cat : tree.Categories)
		printf("\n%s", cat.Name.c_str());

	printf("\n\nMaterial results:\n");
	for(auto mat : tree.Categories[0].Materials)
		printf("\n%s", mat.c_str());

	return EXIT_SUCCESS;
}
